language: ruby
rvm:
- 2.5.3

install: gem install jekyll
script:  gem install bundler -v '~> 1.12' && bundle update rake && jekyll build
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
sudo: false
exclude: [vendor]